/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/admin/account/login": {
    /** POST /api/admin/account/login */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/account/logout": {
    /** POST /api/admin/account/logout */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/account/refresh-token": {
    /** POST /api/admin/account/refresh-token */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/admin-department-mst/list": {
    /** GET /api/admin/admin-department-mst/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/admin-department-mst/update": {
    /** PUT /api/admin/admin-department-mst/update */
    put: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/admin-mst-hist/delete/{id}": {
    /** DELETE /api/admin/admin-mst-hist/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/admin-mst-hist/list": {
    /** GET /api/admin/admin-mst-hist/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/admin-mst-hist/store": {
    /** POST /api/admin/admin-mst-hist/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/admin-mst-hist/update/{id}": {
    /** PUT /api/admin/admin-mst-hist/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/admin-mst/delete/{id}": {
    /** DELETE /api/admin/admin-mst/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/admin-mst/list": {
    /** GET /api/admin/admin-mst/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/admin-mst/store": {
    /** POST /api/admin/admin-mst/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/admin-mst/update/{id}": {
    /** PUT /api/admin/admin-mst/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/admin-role-mst/list": {
    /** GET /api/admin/admin-role-mst/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/admin-role-mst/update": {
    /** PUT /api/admin/admin-role-mst/update */
    put: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/api-mst-hist/delete/{id}": {
    /** DELETE /api/admin/api-mst-hist/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/api-mst-hist/list": {
    /** GET /api/admin/api-mst-hist/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/api-mst-hist/store": {
    /** POST /api/admin/api-mst-hist/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/api-mst-hist/update/{id}": {
    /** PUT /api/admin/api-mst-hist/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/api-mst/delete/{id}": {
    /** DELETE /api/admin/api-mst/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/api-mst/list": {
    /** GET /api/admin/api-mst/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/api-mst/store": {
    /** POST /api/admin/api-mst/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/api-mst/update/{id}": {
    /** PUT /api/admin/api-mst/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/api-role-mst/list": {
    /** GET /api/admin/api-role-mst/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/api-role-mst/update": {
    /** PUT /api/admin/api-role-mst/update */
    put: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/banner-mgmt-hist/delete/{id}": {
    /** DELETE /api/admin/banner-mgmt-hist/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/banner-mgmt-hist/list": {
    /** GET /api/admin/banner-mgmt-hist/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/banner-mgmt-hist/store": {
    /** POST /api/admin/banner-mgmt-hist/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/banner-mgmt-hist/update/{id}": {
    /** PUT /api/admin/banner-mgmt-hist/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/banner-mgmt/delete/{id}": {
    /** DELETE /api/admin/banner-mgmt/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/banner-mgmt/list": {
    /** GET /api/admin/banner-mgmt/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/banner-mgmt/store": {
    /** POST /api/admin/banner-mgmt/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/banner-mgmt/update/{id}": {
    /** PUT /api/admin/banner-mgmt/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/category-mgmt-hist/delete/{id}": {
    /** DELETE /api/admin/category-mgmt-hist/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/category-mgmt-hist/list": {
    /** GET /api/admin/category-mgmt-hist/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/category-mgmt-hist/store": {
    /** POST /api/admin/category-mgmt-hist/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/category-mgmt-hist/update/{id}": {
    /** PUT /api/admin/category-mgmt-hist/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/category-mgmt/delete/{id}": {
    /** DELETE /api/admin/category-mgmt/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/category-mgmt/list": {
    /** GET /api/admin/category-mgmt/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/category-mgmt/store": {
    /** POST /api/admin/category-mgmt/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/category-mgmt/update/{id}": {
    /** PUT /api/admin/category-mgmt/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/category-skill-mgmt/list": {
    /** GET /api/admin/category-skill-mgmt/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/category-skill-mgmt/update": {
    /** PUT /api/admin/category-skill-mgmt/update */
    put: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/department-management-mst/list": {
    /** GET /api/admin/department-management-mst/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/department-management-mst/update": {
    /** PUT /api/admin/department-management-mst/update */
    put: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/department-mst-hist/delete/{id}": {
    /** DELETE /api/admin/department-mst-hist/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/department-mst-hist/list": {
    /** GET /api/admin/department-mst-hist/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/department-mst-hist/store": {
    /** POST /api/admin/department-mst-hist/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/department-mst-hist/update/{id}": {
    /** PUT /api/admin/department-mst-hist/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/department-mst/delete/{id}": {
    /** DELETE /api/admin/department-mst/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/department-mst/list": {
    /** GET /api/admin/department-mst/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/department-mst/store": {
    /** POST /api/admin/department-mst/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/department-mst/update/{id}": {
    /** PUT /api/admin/department-mst/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/feature-mst-hist/delete/{id}": {
    /** DELETE /api/admin/feature-mst-hist/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/feature-mst-hist/list": {
    /** GET /api/admin/feature-mst-hist/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/feature-mst-hist/store": {
    /** POST /api/admin/feature-mst-hist/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/feature-mst-hist/update/{id}": {
    /** PUT /api/admin/feature-mst-hist/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/feature-mst/delete/{id}": {
    /** DELETE /api/admin/feature-mst/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/feature-mst/list": {
    /** GET /api/admin/feature-mst/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/feature-mst/store": {
    /** POST /api/admin/feature-mst/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/feature-mst/update/{id}": {
    /** PUT /api/admin/feature-mst/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/language-mst-hist/delete/{id}": {
    /** DELETE /api/admin/language-mst-hist/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/language-mst-hist/list": {
    /** GET /api/admin/language-mst-hist/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/language-mst-hist/store": {
    /** POST /api/admin/language-mst-hist/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/language-mst-hist/update/{id}": {
    /** PUT /api/admin/language-mst-hist/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/language-mst/delete/{id}": {
    /** DELETE /api/admin/language-mst/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/language-mst/list": {
    /** GET /api/admin/language-mst/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/language-mst/store": {
    /** POST /api/admin/language-mst/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/language-mst/update/{id}": {
    /** PUT /api/admin/language-mst/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/original-translator-mst-hist/delete/{id}": {
    /** DELETE /api/admin/original-translator-mst-hist/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/original-translator-mst-hist/list": {
    /** GET /api/admin/original-translator-mst-hist/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/original-translator-mst-hist/store": {
    /** POST /api/admin/original-translator-mst-hist/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/original-translator-mst-hist/update/{id}": {
    /** PUT /api/admin/original-translator-mst-hist/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/original-translator-mst/delete/{id}": {
    /** DELETE /api/admin/original-translator-mst/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/original-translator-mst/list": {
    /** GET /api/admin/original-translator-mst/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/original-translator-mst/store": {
    /** POST /api/admin/original-translator-mst/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/original-translator-mst/update/{id}": {
    /** PUT /api/admin/original-translator-mst/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/policy-department-mst-hist/delete/{id}": {
    /** DELETE /api/admin/policy-department-mst-hist/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/policy-department-mst-hist/list": {
    /** GET /api/admin/policy-department-mst-hist/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/policy-department-mst-hist/store": {
    /** POST /api/admin/policy-department-mst-hist/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/policy-department-mst-hist/update/{id}": {
    /** PUT /api/admin/policy-department-mst-hist/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/policy-department-mst/delete/{id}": {
    /** DELETE /api/admin/policy-department-mst/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/policy-department-mst/list": {
    /** GET /api/admin/policy-department-mst/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/policy-department-mst/store": {
    /** POST /api/admin/policy-department-mst/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/policy-department-mst/update/{id}": {
    /** PUT /api/admin/policy-department-mst/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/role-mst-hist/delete/{id}": {
    /** DELETE /api/admin/role-mst-hist/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/role-mst-hist/list": {
    /** GET /api/admin/role-mst-hist/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/role-mst-hist/store": {
    /** POST /api/admin/role-mst-hist/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/role-mst-hist/update/{id}": {
    /** PUT /api/admin/role-mst-hist/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/role-mst/delete/{id}": {
    /** DELETE /api/admin/role-mst/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/role-mst/list": {
    /** GET /api/admin/role-mst/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/role-mst/store": {
    /** POST /api/admin/role-mst/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/role-mst/update/{id}": {
    /** PUT /api/admin/role-mst/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/setting-link-mgmt-hist/delete/{id}": {
    /** DELETE /api/admin/setting-link-mgmt-hist/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/setting-link-mgmt-hist/list": {
    /** GET /api/admin/setting-link-mgmt-hist/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/setting-link-mgmt-hist/store": {
    /** POST /api/admin/setting-link-mgmt-hist/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/setting-link-mgmt-hist/update/{id}": {
    /** PUT /api/admin/setting-link-mgmt-hist/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/setting-link-mgmt/delete/{id}": {
    /** DELETE /api/admin/setting-link-mgmt/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/setting-link-mgmt/list": {
    /** GET /api/admin/setting-link-mgmt/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/setting-link-mgmt/store": {
    /** POST /api/admin/setting-link-mgmt/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/setting-link-mgmt/update/{id}": {
    /** PUT /api/admin/setting-link-mgmt/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/skill-description-mgmt-hist/delete/{id}": {
    /** DELETE /api/admin/skill-description-mgmt-hist/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/skill-description-mgmt-hist/list": {
    /** GET /api/admin/skill-description-mgmt-hist/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/skill-description-mgmt-hist/store": {
    /** POST /api/admin/skill-description-mgmt-hist/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/skill-description-mgmt-hist/update/{id}": {
    /** PUT /api/admin/skill-description-mgmt-hist/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/skill-description-mgmt/delete/{id}": {
    /** DELETE /api/admin/skill-description-mgmt/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/skill-description-mgmt/list": {
    /** GET /api/admin/skill-description-mgmt/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/skill-description-mgmt/store": {
    /** POST /api/admin/skill-description-mgmt/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/skill-description-mgmt/update/{id}": {
    /** PUT /api/admin/skill-description-mgmt/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/skill-mgmt-hist/delete/{id}": {
    /** DELETE /api/admin/skill-mgmt-hist/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/skill-mgmt-hist/list": {
    /** GET /api/admin/skill-mgmt-hist/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/skill-mgmt-hist/store": {
    /** POST /api/admin/skill-mgmt-hist/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/skill-mgmt-hist/update/{id}": {
    /** PUT /api/admin/skill-mgmt-hist/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/skill-mgmt/delete/{id}": {
    /** DELETE /api/admin/skill-mgmt/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/skill-mgmt/list": {
    /** GET /api/admin/skill-mgmt/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/skill-mgmt/store": {
    /** POST /api/admin/skill-mgmt/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/skill-mgmt/update/{id}": {
    /** PUT /api/admin/skill-mgmt/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/slider-mgmt-hist/delete/{id}": {
    /** DELETE /api/admin/slider-mgmt-hist/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/slider-mgmt-hist/list": {
    /** GET /api/admin/slider-mgmt-hist/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/slider-mgmt-hist/store": {
    /** POST /api/admin/slider-mgmt-hist/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/slider-mgmt-hist/update/{id}": {
    /** PUT /api/admin/slider-mgmt-hist/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/slider-mgmt/delete/{id}": {
    /** DELETE /api/admin/slider-mgmt/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/slider-mgmt/list": {
    /** GET /api/admin/slider-mgmt/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/slider-mgmt/store": {
    /** POST /api/admin/slider-mgmt/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/slider-mgmt/update/{id}": {
    /** PUT /api/admin/slider-mgmt/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/social-mgmt-hist/delete/{id}": {
    /** DELETE /api/admin/social-mgmt-hist/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/social-mgmt-hist/list": {
    /** GET /api/admin/social-mgmt-hist/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/social-mgmt-hist/store": {
    /** POST /api/admin/social-mgmt-hist/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/social-mgmt-hist/update/{id}": {
    /** PUT /api/admin/social-mgmt-hist/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/social-mgmt/delete/{id}": {
    /** DELETE /api/admin/social-mgmt/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/social-mgmt/list": {
    /** GET /api/admin/social-mgmt/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/social-mgmt/store": {
    /** POST /api/admin/social-mgmt/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/social-mgmt/update/{id}": {
    /** PUT /api/admin/social-mgmt/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/token-mst/delete/{id}": {
    /** DELETE /api/admin/token-mst/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/token-mst/list": {
    /** GET /api/admin/token-mst/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/token-mst/store": {
    /** POST /api/admin/token-mst/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/token-mst/update/{id}": {
    /** PUT /api/admin/token-mst/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/translation-language-mst/list": {
    /** GET /api/admin/translation-language-mst/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/translation-language-mst/update": {
    /** PUT /api/admin/translation-language-mst/update */
    put: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/translation-mst-hist/delete/{id}": {
    /** DELETE /api/admin/translation-mst-hist/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/translation-mst-hist/list": {
    /** GET /api/admin/translation-mst-hist/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/translation-mst-hist/store": {
    /** POST /api/admin/translation-mst-hist/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/translation-mst-hist/update/{id}": {
    /** PUT /api/admin/translation-mst-hist/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/translation-mst/delete/{id}": {
    /** DELETE /api/admin/translation-mst/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/translation-mst/list": {
    /** GET /api/admin/translation-mst/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/translation-mst/store": {
    /** POST /api/admin/translation-mst/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/translation-mst/update/{id}": {
    /** PUT /api/admin/translation-mst/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/user-mgmt-hist/delete/{id}": {
    /** DELETE /api/admin/user-mgmt-hist/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/user-mgmt-hist/list": {
    /** GET /api/admin/user-mgmt-hist/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/user-mgmt-hist/store": {
    /** POST /api/admin/user-mgmt-hist/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/user-mgmt-hist/update/{id}": {
    /** PUT /api/admin/user-mgmt-hist/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/user-mgmt/delete/{id}": {
    /** DELETE /api/admin/user-mgmt/delete/{id} */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/user-mgmt/list": {
    /** GET /api/admin/user-mgmt/list */
    get: {
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/user-mgmt/store": {
    /** POST /api/admin/user-mgmt/store */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
  "/api/admin/user-mgmt/update/{id}": {
    /** PUT /api/admin/user-mgmt/update/{id} */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": Record<string, never>;
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
