version: "3.9"

services:
  php: #Không cần map cổng vì PHP-FPM chỉ giao tiếp nội bộ.
    container_name: pl-php # Setting container name
    build: # Build from docker file config
      context: ./php # . is path from current path
      dockerfile: Dockerfile # Location docker file config to build
    volumes: # Copy file/folder to contianer: (path file/folder):(path in docker env)
      - ../laravel-api:/var/www
    networks:
      - custom_network

  nginx:
    image: nginx:1.27.3
    container_name: webserver-nginx
    volumes:
      - ../laravel-api:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80" # Custom map cổng host 8080 sang container 80, 8080 dùng bên ngoài env docker
    depends_on:
      - php
    networks:
      - custom_network

  db:
    image: postgres:16.6
    container_name: db-pgsql
    ports:
      - "5432:5432" # Custom port cho PostgreSQL 5432 sang 5433, 5433 dùng bên ngoài env docker
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vinh@123 # Ensure this matches the Laravel .env file
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgresql/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./postgresql/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    networks:
      - custom_network

  redis:
    image: redis:latest
    container_name: cache-redis
    ports:
      - "6380:6379" # Custom port cho Redis 6379 sang 6380, 6380 dùng bên ngoài env docker
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge

volumes:
  db-data:
