services:
  ml-php:
    container_name: ml-php
    build: ./laravel
    volumes:
      - ../laravel-api:/var/www/laravel-api
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5433
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      REDIS_HOST: redis
    depends_on:
      - ml-postgres
      - ml-redis

  ml-nginx:
    container_name: ml-nginx
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ../laravel-api:/var/www/laravel-api
      # - ./nextjs-fe:/var/www/nextjs
    ports:
      - "90:80"
    depends_on:
      - ml-php
      # - ml-nextjs
      # - ml-fastapi

  ml-postgres:
    container_name: ml-postgres
    image: postgres:15-alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    environment:
      POSTGRES_DB: ml_db
      POSTGRES_USER: ml_user
      POSTGRES_PASSWORD: ml_password
    ports:
      - "5433:5432"

  ml-redis:
    container_name: ml-redis
    image: redis:alpine
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    ports:
      - "6379:6379"

  # ml-nextjs:
  #   container_name: ml-nextjs
  #   build: ./docker/nextjs
  #   volumes:
  #     - ./nextjs-fe:/app
  #   ports:
  #     - "9003:3000"

  # ml-fastapi:
  #   container_name: ml-fastapi
  #   build: ./docker/fastapi
  #   volumes:
  #     - ./fastapi-app:/app
  #   ports:
  #     - "9002:8000"
  #   depends_on:
  #     - postgres