server {
    listen 80;
    server_name localhost;

    location ^~ /api/ {
        root /var/www/laravel-api/public;
        try_files $uri $uri/ @laravel;
        location ~ \.php$ {
            fastcgi_pass ml-php:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }

    location @laravel {
        rewrite ^.*$ /index.php last;
    }

    # location ^~ /fastapi/ {
    #     proxy_pass http://ml-fastapi:8000/;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    # }

    # location / {
    #     proxy_pass http://ml-nextjs:3000/;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    # }
}