import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "../store/Provider";
import ThemeProvider from "@/components/layout/ThemeProvider";
import MasterLayout from "@/components/layout/MasterLayout";
import ToastProvider from "@/components/ui/ToastProvider";
import DevConsoleFilter from '@/components/dev/DevConsoleFilter'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  // Do not set theme-related attributes on the server-rendered <html> element.
  // The `next-themes` provider injects a script that updates `document.documentElement`
  // at runtime (based on localStorage or system preference). That script may
  // mutate the `<html>` attributes before React hydrates which causes React to
  // log a hydration mismatch warning. We add `suppressHydrationWarning` here to
  // avoid that noisy warning for the root element.
  <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <ThemeProvider>
            <ToastProvider>
              <DevConsoleFilter />
              <MasterLayout>{children}</MasterLayout>
            </ToastProvider>
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
